apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: private-azurefile-csi-logs
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  resourceGroup: test_keda_airflow_rg
  storageAccount: testkedaairflowsa
  shareName: airflow-logs
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - nosharesock
  - actimeo=30
